# Generated by Django 5.0.7 on 2024-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name=' نام خانوادگی')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس')),
                ('phone_number', models.IntegerField(max_length=20, verbose_name='شماره تماس')),
            ],
        ),
    ]
