# Generated by Django 5.0.7 on 2024-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': ' مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AddField(
            model_name='customeruser',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='رمز عبور'),
        ),
    ]
