# Generated by Django 5.0.7 on 2024-08-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_options_customeruser_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
    ]
