# Generated by Django 5.0.7 on 2024-08-09 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customeruser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': ' کاربر', 'verbose_name_plural': ' کاربران '},
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.BigIntegerField(null=True, verbose_name='شماره تماس'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس')),
                ('phone_number', models.BigIntegerField(null=True, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
    ]
