# Generated by Django 5.0.7 on 2024-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_alter_payment_customer_alter_shipment_customer_and_more'),
        ('orders', '0006_alter_cart_customer_alter_cart_product_and_more'),
        ('users', '0006_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
