# Generated by Django 5.0.7 on 2024-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_customuser_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
