# Generated by Django 5.0.7 on 2024-08-12 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پرداخت')),
                ('Payment_meto', models.CharField(blank=True, max_length=100, null=True, verbose_name='متد پرداختی')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': '  پرداختها ',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='شهر')),
                ('state', models.CharField(max_length=20, null=True, verbose_name='استان')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='کشور')),
                ('zip_code', models.IntegerField(null=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'حمل و نقل',
                'verbose_name_plural': ' حمل و نقل ها ',
            },
        ),
    ]
