# Generated by Django 5.0.7 on 2024-08-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('Payment_meto', models.CharField(max_length=100, verbose_name='متد پرداختی')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('state', models.CharField(max_length=20, verbose_name='استان')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('zip_code', models.CharField(max_length=10, verbose_name='کد')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
