# Generated by Django 5.0.7 on 2024-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_date',
            new_name='payment_date',
        ),
    ]
