# Generated by Django 5.0.7 on 2024-08-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_rename_payment_date_payment_payment_date'),
        ('users', '0003_alter_customer_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'حمل و نقل'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_meto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متد پرداختی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='state',
            field=models.CharField(max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='کد'),
        ),
    ]
