# Generated by Django 5.0.7 on 2024-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_payment_options_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='کد'),
        ),
    ]
