# Generated by Django 5.0.7 on 2024-08-05 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_shipment_shipment_date_alter_shipment_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': '  پرداختها '},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'حمل و نقل', 'verbose_name_plural': ' حمل و نقل ها '},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پرداخت'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ارسال'),
        ),
    ]
