# Generated by Django 5.0.7 on 2024-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': ' کارت',
                'verbose_name_plural': ' کارت ها ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت کل')),
            ],
            options={
                'verbose_name': ' سفارش ',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=' تعداد ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت ')),
            ],
            options={
                'verbose_name': ' آیتم سفارش',
                'verbose_name_plural': 'آیتم های سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ' علاقه مندی ',
                'verbose_name_plural': 'علاقه مندی ها ',
            },
        ),
    ]
