# Generated by Django 5.0.7 on 2024-08-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_payment_options_alter_shipment_options_and_more'),
        ('orders', '0001_initial'),
        ('products', '0003_alter_category_options_alter_product_options_and_more'),
        ('users', '0003_alter_customer_options_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': ' کارت'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': ' سفارش ', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='order_item',
            options={'verbose_name': ' آیتم سفارش', 'verbose_name_plural': 'آیتم های سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': ' علاقه مندی ها'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.shipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت '),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
