# Generated by Django 5.0.7 on 2024-08-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': ' کارت', 'verbose_name_plural': ' کارت ها '},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': ' علاقه مندی ', 'verbose_name_plural': 'علاقه مندی ها '},
        ),
    ]
