# Generated by Django 5.0.7 on 2024-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_options_alter_wishlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': ' سفارش ', 'verbose_name_plural': 'سفارشات'},
        ),
    ]
